name: Publish release
on:
  push:
    branches:
      - master

env:
  ELECTRON_IS_DEV: 0
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CSC_LINK: ${{ secrets.CODE_SIGNING_CERTIFICATE }}
  CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}

jobs:
  release-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node environment
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: 'npm'
      - run: npm ci

      - name: Setup Certificates
        run: |
            echo $CSC_LINK | base64 --decode > certificate.p12 
            security create-keychain -p GITHUB build.keychain
            security default-keychain -s build.keychain
            security unlock-keychain -p GITHUB build.keychain
            security import certificate.p12 -k build.keychain -P $CSC_KEY_PASSWORD -T /usr/bin/codesign;
            security set-key-partition-list -S apple-tool:,apple: -s -k GITHUB build.keychain
            rm -rf *.p12

      - name: publish
        run: npm run publish-mac

  release-win:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install build dependencies
        run: | 
          sudo apt update
          sudo apt-get install --no-install-recommends -y libopenjp2-tools wine32
      - name: Setup Node environment
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: 'npm'
      - run: npm ci
      - name: publish
        run: npm run publish-win