name: Publish release
on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node environment
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: 'npm'
      - run: npm ci

      - name: publish
        run: npm run publish-ci

        env:
          ELECTRON_IS_DEV: 0
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_LINK: ${{ secrets.CODE_SIGNING_CERTIFICATE }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
